name: workflow-name
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job-name:
    runs-on: ubuntu-latest
    
    services:
      service-name-1:
        image: venseven07/mock_weather_server
        ports:
           - 8080:80
    steps:
      - name: Get from service-1
        run: curl "http://127.0.0.1:80/data/2.5/weather?lat=44.56&lon=123.26&appid=d8310c9fbcfaee650d22017af4646e00"
