name: workflow-name
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job-name:
    runs-on: ubuntu-latest
    env:
      working-directory: ./mock_server
      
    steps:
      - uses: actions/checkout@main
      - name: requirements file install
        run:  pip3 install -r ./mock_server/requirements.txt

