name: workflow-name
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job-name:
    runs-on: ubuntu-latest
    
    services:
      service-name-1:
        image: venseven07/mock_weather_server
        ports:
           - 8081:80
    steps:
      - name: Get from service-1
        run: |
          curl www.google.com
