name: workflow-name
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run:  cat README.md
