name: workflow-name
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job-name:
    runs-on: ubuntu-latest
    
    services:
      service-name-1:
        image: digitalocean/flask-helloworld
        ports:
           - 5000:5000
    steps:
      - name: Get from service-1
        run: curl -X GET "http://127.0.0.1:5000/"
