name: workflow-name
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job-name:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@main
    - name: requirements file install
      run:  |
          pip3 install -r ./mock_server/requirements.txt
          uvicorn mock_server.main:app --reload&
    - name: build test
      run: swift build -v
      working-directory: ./MyLibrary 
    - name: Run tests
      run: swift test -v
      working-directory: ./MyLibrary 

