name: workflow-name
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job-name:
    runs-on: ubuntu-latest
    
    services:
      service-name-1:
        image: venseven07/mock_weather_server
        ports:
           - 8081:80
    steps:
      - name: Get from service-1
        run: curl -X GET "http://0.0.0.0:8081/data/2.5/weather?lat=44.56&lon=123.26&appid=d8310c9fbcfaee650d22017af646e00" | jq
