name: workflow-name
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job-name:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@main
    - name: requirements file install
      run:  |
          npm install express
          node index.js&
      working-directory: ./mockjs
    
    - name: curl
      run: curl "http://0.0.0.0:8000/data/2.5/weather"

