name: workflow-name
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job-name:
    runs-on: ubuntu-latest
    env:
      working-directory: ./mock_server
      
    steps:
      - uses: actions/checkout@main
      - name: print
        run:  ls
        working-directory: $((env.working-directory))
      - name: print
        run:  ls - R
